F make receive station html
dsc-ucu-lviv/hvalue pull request #40
Opened 2020-04-15 16:14 UTC by denysgerasymuk799

Could you check my styles and colors. Write some comments to fix them

2020-04-25 13:42 UTC, elenalazarus requested changes
1) Very uncomfortable position of the window. Place it in the middle until the profile of the organisation is fully created
2) Categories field does not coincide with one at the mockup

2020-04-29 05:23 UTC, alazaniia commented on web_server/receive_form.py
> +                return input_data
Don't return it yet.

2020-04-29 06:42 UTC, alazaniia requested changes

2020-04-29 06:42 UTC, alazaniia commented on web_server/static/style_for_receive_station.css
> +}
```
ul.chosen-choices {
    border-radius: 10px;
    min-height: 40px;
    display: flex;
    align-items: center;
}

li.search-choice > span {
    font-family: inherit;
    font-weight: normal;
    font-size: 110%;
}


ul.chosen-choices > li.search.choice {
    border-radius: 10px;
}


ul.chosen-choices > li {
    display: flex;
    align-items: center;
}

select {
    background-color: white;
}

div.checkboxes {
    text-align: left;
}

div.chosen-container, div.chosen-container-multi {
    margin: 8px 0;
}
```

2020-04-29 06:42 UTC, alazaniia commented on web_server/static/style_for_receive_station.css
> +
```
div.calender > input {
    border-radius: 10px;
    border-color: transparent;
}
```

2020-04-29 06:42 UTC, alazaniia commented on web_server/static/style_for_receive_station.css
> +    border: 1px var(--light-powder);
```
    display: flex;
    border: solid 1px var(--grey);
```

2020-04-29 06:42 UTC, alazaniia commented on web_server/static/style_for_receive_station.css
> +    padding: 12px 20px;
```
    padding-left: 12px;
```

2020-04-29 13:13 UTC, alazaniia approved these changes
good job

2020-04-29 13:13 UTC, alazaniia commented on web_server/static/style_for_receive_station.css
please add this to align the Categories* label
```
div.checkboxes {
    text-align: left;
}
```

2020-04-29 13:37 UTC, sofiia-tesliuk requested changes
Please, finish fixes, commented above

2020-04-29 13:39 UTC, sofiia-tesliuk approved these changes

2020-04-29 13:44 UTC, LAnastasiia approved these changes

2020-04-29 13:44 UTC, merged